_wandb:
    value:
        cli_version: 0.22.1
        e:
            vljxlrogstt8wjoi8so0iawzupxivsjr:
                args:
                    - --use_wandb
                    - --impl=warp
                    - --num_timesteps=800000000
                codePath: learning/train_jax_ppo.py
                codePathLocal: learning/train_jax_ppo.py
                cpu_count: 64
                cpu_count_logical: 64
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "104806400000"
                        used: "40388038656"
                email: lucmccutcheon.home@gmail.com
                executable: /mnt/fast/nobackup/users/lm01065/grad_decay/grad_playground/.venv/bin/python
                git:
                    commit: ecdff82ae4cde5ab0075b9b5fac902fdbce90ba9
                    remote: https://github.com/LucMc/grad_playground.git
                gpu: NVIDIA GeForce RTX 3090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-bf4ea017-744a-d3b1-f748-c90195fec436
                host: aisurrey14.surrey.ac.uk
                memory:
                    total: "540886478848"
                os: Linux-4.18.0-477.10.1.el8_8.x86_64-x86_64-with-glibc2.28
                program: /mnt/fast/nobackup/users/lm01065/grad_decay/grad_playground/learning/train_jax_ppo.py
                python: CPython 3.12.9
                root: /mnt/fast/nobackup/users/lm01065/grad_decay/grad_playground
                slurm:
                    array_job_id: "1444209"
                    array_task_count: "1"
                    array_task_id: "0"
                    array_task_max: "0"
                    array_task_min: "0"
                    array_task_step: "1"
                    cluster_name: aisurrey
                    conf: /etc/slurm/slurm.conf
                    cpus_on_node: "10"
                    cpus_per_task: "10"
                    gpus: "1"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: uos
                    job_cpus_per_node: "10"
                    job_end_time: "1759702525"
                    job_gid: "5000001"
                    job_gpus: "2"
                    job_id: "1444209"
                    job_name: multi_algo_train
                    job_nodelist: aisurrey14
                    job_num_nodes: "1"
                    job_partition: "3090"
                    job_qos: normal
                    job_start_time: "1759446925"
                    job_uid: "275948"
                    job_user: lm01065
                    jobid: "1444209"
                    localid: "0"
                    mem_per_node: "24576"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: aisurrey14
                    nprocs: "1"
                    ntasks: "1"
                    ntasks_per_node: "1"
                    prio_process: "0"
                    procid: "0"
                    submit_dir: /mnt/fast/nobackup/users/lm01065/grad_decay/grad_playground
                    submit_host: aisurrey-submit01.surrey.ac.uk
                    task_pid: "3670364"
                    tasks_per_node: "1"
                    topology_addr: aisurrey14
                    topology_addr_pattern: node
                    tres_per_task: cpu=10
                startedAt: "2025-10-02T23:15:54.971311Z"
                writerId: vljxlrogstt8wjoi8so0iawzupxivsjr
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 12
                - 45
            "2":
                - 12
                - 45
            "3":
                - 13
            "4": 3.12.9
            "5": 0.22.1
            "12": 0.22.1
            "13": linux-x86_64
action_repeat:
    value: 1
action_scale:
    value: 0.5
ctrl_dt:
    value: 0.05
ema_alpha:
    value: 1
env_name:
    value: LeapCubeReorient
episode_length:
    value: 1000
history_len:
    value: 1
impl:
    value: warp
nconmax:
    value: 245760
njmax:
    value: 128
obs_noise:
    value:
        level: 1
        random_ori_injection_prob: 0
        scales:
            cube_ori: 0.1
            cube_pos: 0.02
            joint_pos: 0.05
pert_config:
    value:
        angular_velocity_pert:
            - 0
            - 0.5
        enable: false
        linear_velocity_pert:
            - 0
            - 3
        pert_duration_steps:
            - 1
            - 100
        pert_wait_steps:
            - 60
            - 150
reward_config:
    value:
        scales:
            action_rate: -0.001
            energy: -0.001
            hand_pose: -0.5
            joint_vel: 0
            orientation: 5
            position: 0.5
            termination: -100
        success_reward: 100
sim_dt:
    value: 0.01
success_threshold:
    value: 0.1
