_wandb:
    value:
        cli_version: 0.21.0
        e:
            2fylx3fpoc7yilqqybrj0xrzezos48ix:
                args:
                    - --optim
                    - adam
                    - --num_timesteps
                    - "800000000"
                    - --use_wandb
                    - --impl=warp
                    - --num_envs
                    - "256"
                codePath: learning/train_jax_ppo.py
                codePathLocal: learning/train_jax_ppo.py
                cpu_count: 64
                cpu_count_logical: 64
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "107307073536"
                        used: "33564618752"
                email: lucmccutcheon.home@gmail.com
                executable: /mnt/fast/nobackup/users/lm01065/.venv/bin/python
                git:
                    commit: 2c7f1c9190e0658a7a0e930c1fc3294646ba80c8
                    remote: https://github.com/LucMc/grad_playground.git
                gpu: NVIDIA GeForce RTX 3090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-d7f6ca00-2b7a-108d-74a0-19f2fb497281
                host: aisurrey11.surrey.ac.uk
                memory:
                    total: "540885753856"
                os: Linux-5.14.0-427.42.1.el9_4.x86_64-x86_64-with-glibc2.34
                program: /mnt/fast/nobackup/users/lm01065/grad_decay/grad_playground/learning/train_jax_ppo.py
                python: CPython 3.12.5
                root: /mnt/fast/nobackup/users/lm01065/grad_decay/grad_playground
                slurm:
                    cluster_name: aisurrey
                    conf: /etc/slurm/slurm.conf
                    cpu_bind: quiet,mask_cpu:0x00000000000000FF
                    cpu_bind_list: "0x00000000000000FF"
                    cpu_bind_type: 'mask_cpu:'
                    cpu_bind_verbose: quiet
                    cpus_on_node: "8"
                    cpus_per_task: "8"
                    distribution: block
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: uos
                    job_cpus_per_node: "8"
                    job_end_time: "1759512542"
                    job_gid: "5000001"
                    job_group: A-ER01-PGR
                    job_id: "1450263"
                    job_name: bash
                    job_nodelist: aisurrey11
                    job_num_nodes: "1"
                    job_partition: "3090"
                    job_qos: normal
                    job_start_time: "1759498142"
                    job_uid: "275948"
                    job_user: lm01065
                    jobid: "1450263"
                    launch_node_ipaddr: 131.227.81.143
                    localid: "0"
                    mem_per_node: "32768"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: aisurrey11
                    nprocs: "1"
                    ntasks: "1"
                    prio_process: "0"
                    procid: "0"
                    pty_port: "42873"
                    pty_win_col: "209"
                    pty_win_row: "51"
                    srun_comm_host: 131.227.81.143
                    srun_comm_port: "42874"
                    step_gpus: "0"
                    step_id: "0"
                    step_launcher_port: "42874"
                    step_nodelist: aisurrey11
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "0"
                    submit_dir: /mnt/fast/nobackup/users/lm01065/grad_decay/grad_playground
                    submit_host: aisurrey-submit01.surrey.ac.uk
                    task_pid: "237224"
                    tasks_per_node: "1"
                    topology_addr: aisurrey11
                    topology_addr_pattern: node
                    tres_per_task: cpu=8
                    umask: "0022"
                startedAt: "2025-10-03T13:43:11.165352Z"
                writerId: 2fylx3fpoc7yilqqybrj0xrzezos48ix
        m: []
        python_version: 3.12.5
        t:
            "1":
                - 12
                - 45
            "2":
                - 12
                - 45
            "3":
                - 13
            "4": 3.12.5
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
action_repeat:
    value: 1
action_scale:
    value: 0.5
ctrl_dt:
    value: 0.05
ema_alpha:
    value: 1
env_name:
    value: LeapCubeReorient
episode_length:
    value: 1000
history_len:
    value: 1
impl:
    value: warp
nconmax:
    value: 245760
njmax:
    value: 128
obs_noise:
    value:
        level: 1
        random_ori_injection_prob: 0
        scales:
            cube_ori: 0.1
            cube_pos: 0.02
            joint_pos: 0.05
optim:
    value: adam
pert_config:
    value:
        angular_velocity_pert:
            - 0
            - 0.5
        enable: false
        linear_velocity_pert:
            - 0
            - 3
        pert_duration_steps:
            - 1
            - 100
        pert_wait_steps:
            - 60
            - 150
reward_config:
    value:
        scales:
            action_rate: -0.001
            energy: -0.001
            hand_pose: -0.5
            joint_vel: 0
            orientation: 5
            position: 0.5
            termination: -100
        success_reward: 100
sim_dt:
    value: 0.01
success_threshold:
    value: 0.1
