_wandb:
    value:
        cli_version: 0.22.1
        e:
            cfocujm9gofcuy7ahnzaae46xec9izyi:
                args:
                    - --env_name
                    - Go1JoystickFlatTerrain
                    - --use_wandb
                codePath: learning/train_jax_ppo.py
                codePathLocal: learning/train_jax_ppo.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "1081101176832"
                        used: "171408273408"
                email: lucmccutcheon.home@gmail.com
                executable: /home/dook/grad_decay/.venv/bin/python3
                git:
                    commit: 8356c84f3b682f2e5602f131fa4eec831632498c
                    remote: https://github.com/google-deepmind/mujoco_playground.git
                gpu: NVIDIA GeForce RTX 3080
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      memoryTotal: "10737418240"
                      name: NVIDIA GeForce RTX 3080
                      uuid: GPU-0a89f444-1e36-a486-2588-e6c6382b12be
                host: DESKTOP-MPAPUU0
                memory:
                    total: "33603907584"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.35
                program: /home/dook/mujoco_playground/learning/train_jax_ppo.py
                python: CPython 3.11.0rc1
                root: /home/dook/mujoco_playground
                startedAt: "2025-10-01T18:08:10.186297Z"
                writerId: cfocujm9gofcuy7ahnzaae46xec9izyi
        m: []
        python_version: 3.11.0rc1
        t:
            "1":
                - 1
                - 12
                - 45
            "2":
                - 1
                - 12
                - 45
            "3":
                - 13
                - 61
            "4": 3.11.0rc1
            "5": 0.22.1
            "12": 0.22.1
            "13": linux-x86_64
Kd:
    value: 0.5
Kp:
    value: 35
action_repeat:
    value: 1
action_scale:
    value: 0.5
command_config:
    value:
        a:
            - 1.5
            - 0.8
            - 1.2
        b:
            - 0.9
            - 0.25
            - 0.5
ctrl_dt:
    value: 0.02
env_name:
    value: Go1JoystickFlatTerrain
episode_length:
    value: 1000
history_len:
    value: 1
impl:
    value: jax
nconmax:
    value: 32768
njmax:
    value: 40
noise_config:
    value:
        level: 1
        scales:
            gravity: 0.05
            gyro: 0.2
            joint_pos: 0.03
            joint_vel: 1.5
            linvel: 0.1
pert_config:
    value:
        enable: false
        kick_durations:
            - 0.05
            - 0.2
        kick_wait_times:
            - 1
            - 3
        velocity_kick:
            - 0
            - 3
reward_config:
    value:
        max_foot_height: 0.1
        scales:
            action_rate: -0.01
            ang_vel_xy: -0.05
            dof_pos_limits: -1
            energy: -0.001
            feet_air_time: 0.1
            feet_clearance: -2
            feet_height: -0.2
            feet_slip: -0.1
            lin_vel_z: -0.5
            orientation: -5
            pose: 0.5
            stand_still: -1
            termination: -1
            torques: -0.0002
            tracking_ang_vel: 0.5
            tracking_lin_vel: 1
        tracking_sigma: 0.25
sim_dt:
    value: 0.004
soft_joint_pos_limit_factor:
    value: 0.95
