_wandb:
    value:
        cli_version: 0.22.1
        e:
            ite8myyww7dbudn1b8ghe1ck2us04xvm:
                args:
                    - --env_name
                    - CheetahRun
                    - --use_wandb
                    - --num_timesteps
                    - "800000000"
                codePath: learning/train_jax_ppo.py
                codePathLocal: learning/train_jax_ppo.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "1081101176832"
                        used: "171903004672"
                email: lucmccutcheon.home@gmail.com
                executable: /home/dook/mujoco_playground/.venv/bin/python3
                git:
                    commit: 8356c84f3b682f2e5602f131fa4eec831632498c
                    remote: https://github.com/google-deepmind/mujoco_playground.git
                gpu: NVIDIA GeForce RTX 3080
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      memoryTotal: "10737418240"
                      name: NVIDIA GeForce RTX 3080
                      uuid: GPU-0a89f444-1e36-a486-2588-e6c6382b12be
                host: DESKTOP-MPAPUU0
                memory:
                    total: "33603911680"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.35
                program: /home/dook/mujoco_playground/learning/train_jax_ppo.py
                python: CPython 3.11.0rc1
                root: /home/dook/mujoco_playground
                startedAt: "2025-10-02T16:14:04.697861Z"
                writerId: ite8myyww7dbudn1b8ghe1ck2us04xvm
        m: []
        python_version: 3.11.0rc1
        t:
            "1":
                - 12
                - 45
            "2":
                - 12
                - 45
            "3":
                - 13
            "4": 3.11.0rc1
            "5": 0.22.1
            "12": 0.22.1
            "13": linux-x86_64
action_repeat:
    value: 1
ctrl_dt:
    value: 0.01
env_name:
    value: CheetahRun
episode_length:
    value: 1000
impl:
    value: jax
nconmax:
    value: 100000
njmax:
    value: 100
sim_dt:
    value: 0.01
vision:
    value: false
