_wandb:
    value:
        cli_version: 0.22.1
        e:
            nyz61s976po044wbb1vyc4p1xpn9v11n:
                args:
                    - --optim
                    - adam_gwd
                    - --num_timesteps
                    - "800_000_000"
                    - --use_wandb
                codePath: learning/train_jax_ppo.py
                codePathLocal: learning/train_jax_ppo.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "1081101176832"
                        used: "187003240448"
                email: lucmccutcheon.home@gmail.com
                executable: /home/dook/mujoco_playground/.venv/bin/python3
                git:
                    commit: d5cbccbc77c2ec210ba953e1e7a52deb8c077836
                    remote: https://github.com/LucMc/grad_playground.git
                gpu: NVIDIA GeForce RTX 3080
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      memoryTotal: "10737418240"
                      name: NVIDIA GeForce RTX 3080
                      uuid: GPU-0a89f444-1e36-a486-2588-e6c6382b12be
                host: DESKTOP-MPAPUU0
                memory:
                    total: "33603907584"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.35
                program: /home/dook/mujoco_playground/learning/train_jax_ppo.py
                python: CPython 3.11.0rc1
                root: /home/dook/mujoco_playground
                startedAt: "2025-10-04T20:34:45.586063Z"
                writerId: nyz61s976po044wbb1vyc4p1xpn9v11n
        m: []
        python_version: 3.11.0rc1
        t:
            "1":
                - 12
                - 45
            "2":
                - 12
                - 45
            "3":
                - 13
            "4": 3.11.0rc1
            "5": 0.22.1
            "12": 0.22.1
            "13": linux-x86_64
action_repeat:
    value: 1
action_scale:
    value: 0.5
ctrl_dt:
    value: 0.05
ema_alpha:
    value: 1
env_name:
    value: LeapCubeReorient
episode_length:
    value: 1000
history_len:
    value: 1
impl:
    value: jax
nconmax:
    value: 245760
njmax:
    value: 128
obs_noise:
    value:
        level: 1
        random_ori_injection_prob: 0
        scales:
            cube_ori: 0.1
            cube_pos: 0.02
            joint_pos: 0.05
optim:
    value: adam_gwd
pert_config:
    value:
        angular_velocity_pert:
            - 0
            - 0.5
        enable: false
        linear_velocity_pert:
            - 0
            - 3
        pert_duration_steps:
            - 1
            - 100
        pert_wait_steps:
            - 60
            - 150
reward_config:
    value:
        scales:
            action_rate: -0.001
            energy: -0.001
            hand_pose: -0.5
            joint_vel: 0
            orientation: 5
            position: 0.5
            termination: -100
        success_reward: 100
sim_dt:
    value: 0.01
success_threshold:
    value: 0.1
